version: '3.1'
services:
  memcached:
    image: 'memcached:alpine'
    networks:
      - svt_net
  redis:
    image: 'redis:alpine'
    networks:
      - svt_net
  mysql:
    image: 'mysql:5.5'
    working_dir: /application
    volumes:
      - '/home/volumes/listadostour/mysql/data:/var/lib/mysql:rw'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - svt_net

  webserver:
    image: 'nginx:alpine'
    container_name: 'web_prod_360'
    working_dir: /application
    volumes:
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - app_public:/application/public:ro
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      # - VIRTUAL_HOST=${VIRTUAL_HOST}
      # - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      # - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - svt_net
      - nginx-proxy_default
    depends_on:
      - php-fpm

  php-fpm:
    image: listados/site_360:1.0.3
    working_dir: /application
    container_name: 'php_prod_360'
    volumes:
      - './locale:/usr/share/locale'
      - ./.env:/application/.env:ro
      - './phpdocker/php-fpm/locale.gen:/etc/locale.gen'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini'
      - app_public:/application/public
    networks:
      - svt_net


volumes:
  app_public:
    driver: local

networks:
  nginx-proxy_default:
    external: true
  svt_net:
