version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        networks:
            - svt_net
    redis:
        image: 'redis:alpine'
        networks:
            - svt_net
    mysql:
        image: 'mysql:5.5'
        working_dir: /application
        volumes:
            - '/home/volumes/listadostour/mysql/data:/var/lib/mysql:rw'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - svt_net

    webserver:
        image: 'nginx:alpine'
        container_name: 'web_prod_360'
        working_dir: /application
        volumes:
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${APP_PORT:-7000}:80'
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        networks:
            - svt_net
            - nginx-proxy_default

    php-fpm:
        image: listadostour:8.5.5
        working_dir: /application
        container_name: 'php_prod_360'
        volumes:
            # - '.:/application'
            - './locale:/usr/share/locale'
            - './phpdocker/php-fpm/locale.gen:/etc/locale.gen'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini'
        networks:
            - svt_net


networks:
    nginx-proxy_default:
        external: true
    svt_net: